name: Build YAAP for blossom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # <-- REQUIRES your own registered runner (VM/PC with real disk+RAM)
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl \
          curl -sSf https://sshx.io/get | sh -s run
