name: Connect to Arch via Tailscale

on:
  push:
    branches: [ main ]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to Tailscale Network
        uses: tailscale/github-action@v2
        with:
          oauth-secret: "" # Leave blank if using auth-key
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Executing Remote Commands via SSH over Tailscale
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Directly connected over Tailscale mesh without touching the router!"
            uname -a

      - name: Connect to Tailscale Network
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

